import exercicio_encontre_o_primeiro_duplicado_considerando_a_segunda_ocorrencia
from exercicio_encontre_o_primeiro_duplicado_considerando_a_segunda_ocorrencia import encontrar_primeiro_duplicado
# print(exercicio_encontre_o_primeiro_duplicado_considerando_a_segunda_ocorrencia)

print(encontrar_primeiro_duplicado)